### ISSUE TITLE
Matching App-Name and UI.

### ISSUE THREAD

**Issue by sirrooster** [Magisk-Modules-Alt-Repo/HideNavBar#86]
I was searching 10 hours for the module: "DisableGestureNavigation"
Now I found it here with complete different name: "HideNavBar" aka "NavTweaks"
(confusing names)

I am using LA18.1 on Galaxy S5. There is no NavBar, nothing to hide. And no settings to disable the annoying gesture "return to last app" when swiping from the left Bottom edge. So it was impossible to scoll my Media Player, which has the time-scoll-bar at the bottom of the screen.
Now the annying "back" gesture is finaly off. Yeah :-)
Thanx!!!

Issue: During my seach I found many users looking for a solution of this problem.
I think they all fail to find this module because of the confusing naming.

btw: UI to change and control setting would be comfortable.

**Comment by DanGLES3** [comment]
1-Had to change the name because my module now also offers options for those who don't want to hide the navigation bar, so hidenavbar would not encompass what it is about, if you have a better name suggestion I'm all ears

2-I'm not an app developer so I don't have the programming skills required to make an app
